language: node_js
compiler: gcc
dist: trusty

node_js:
- '8'

before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who

install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "ADdYKXiVBo+Vbk5htq5JJynLSP5aQh//6RbkqqjAX2dRK1EPkQu5DGqljKw2hp8oLhkeeLpc2drRLmkLBlyPsHvbVwCc2lnE2+RibHQA3z4sT4//PNwlfG6NMnry6PVh2yZHhE0hHKCrnIGYywWZzm+YsGQ/0lihTB52gY782WuOix/0vEd26qXJt76TQmXwMBdfnwAWmK1M4fcdIhwWNEhm57MDs6CJPUj8e9JoEW2YpmEYv3bIOh8SHnAqDVq2bAGIDdKLrhqpPZZuHyI53uBsfT3bmjT7byC3Cu7ztBoRqBDEx4QFHlYi4LfT0snse3iiXAFdYBKCg/KDFGbOPGRyGM7G0n74+3DouYegJ1pe3YNPM27eyyaSBsHyNEJK2nwCLa4ub+0ZAcnT2HUNx6CrxMfMr5nJZPDtJlxi5AIHR/oPzF1vjADLz7IrjAZKbO5hezOqyCPieSa1ldSY8I2EBhuKDuMvPquEY3QyiRE5xM9zkXzU3CAVBIiDhMtQVZ8jLLno0lk1Znoq58Z5tvpT4dRYwvAa1unnCKzSDBb6OmUUVRmldcJ6bxIy2/GUOjRc3KcLMnF3Im2gdkl2/ogtOGUykXAp/+hLouE8872/zIFgf2uHQ2hrl2twE8xlr6aDbNMrPgCRp2/KCLcnHdIsVRB5f949lbugqeUbaCA="
env:
  secure: "3OOADEmObMqPmIZfwWpwfTbXH4gSFEnzN8JFvOwwte5TE/MUC2yTv1cuZas4XkIcq8CQC09srkIHZnu0BAGvW/nzY45Q4lKz7W4uT9j6kTdfIQG2v2cC58EcKBU2g0NgSW5BlhKx6DyeGzaqcVfI4l8hsAOwiqdUY1wY5snzM0TWB0hXXBA8ezvLkY9Q7pn/xRcBAYWKjO2zGlUvT8Ri+VKjwjP6V+1FVQIs4DAsxImIea4Mpeaq909UAF+CquaUhGrUC27hz1G4RclAjVdwHfC+4kkMDUCOWJMEVLk1b/pvlcxV0kmoktnWgDIl24QCtpCU/g9v6UG6tqOJJ2F+j8xcs6EY6bv/ryJF7jcje7RVvlQCzMHECUzjhoaBGxwiDRUQjlHUc26B/dK9jx4uUtURbRM6fA0AWRiubXqiVzowD8/d9ziBF9qug8C5TopHQGnMv0zTubkQ+mf4DV5uyLhrHP4v6S8GFsuY3rmNRhZwlLkJZwt2OdVjhU5CxY9LShAk2284qBd4DFdgprAwzArCF7JaUshiauMhW4+RFJmFe/A0a+mo1by9ahj+q72mO1FFtXdhhIdK/x827zpnEOHmPezLjG23cPf7F8x/RAmwLlYPgluW9WLA+Ueuj7cNdEG1e/Vdbvnq5owFFC26ihrlUc3nlBww/S0nVrh8ps8="
